config/routes.rb
Rails.application.routes.draw do
  resources :podcasts do
    member do
      get 'export'
    end
  end

  root 'podcasts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  def index
    @columns = PodcastDatatable.columns

    respond_to do |format|
      format.html
      format.json { render json: PodcastDatatable.new(view_context) }
    end
  end

  def export
    @category = params[:id]
    @podcasts = Podcast.where(category: @category, done: [nil, false])
  end

  def show
  end

  def new
    @podcast = Podcast.new
  end

  def edit
  end

  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    def podcast_params
      params.require(:podcast).permit(:title, :category, :itunes_url, :feed_url, :failed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ItunesPodcasts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/podcasts/_form.html.erb
<%= form_for(podcast) do |f| %>
  <% if podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% podcast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :itunes_url %>
    <%= f.text_field :itunes_url %>
  </div>

  <div class="field">
    <%= f.label :feed_url %>
    <%= f.text_field :feed_url %>
  </div>

  <div class="field">
    <%= f.label :failed %>
    <%= f.check_box :failed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/export.html.erb
<%= @podcasts.count %> Podcasts in category <%= @category %>

app/views/podcasts/export.xml.erb
<?xml version='1.0' encoding='utf-8' standalone='no' ?>
<opml version="1.1">
  <head>
    <title>Podcast Feeds</title>
    <dateCreated><%= Time.now() %></dateCreated>
    <dateModified><%= Time.now() %> </dateModified>
  </head>

  <body>
    <outline text="<%= @category %>">
      <% @podcasts.each do |podcast| %>
        <outline text="<%= podcast.title %>" xmlUrl="<%= podcast.feed_url %>" type="rss" />
      <% end %>
    </outline>
  </body>
</opml>

app/views/podcasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Podcasts</h1>

<table id='datatable'
       class="display nowrap"
       cellspacing="0"
       width="100%"
       data-source="<%= podcasts_path(format: :json) %>">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Category</th>
      <th>Itunes url</th>
      <th>Feed url</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Failed</th>
      <th>done</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<br>

<script>
  $(document).ready( function () {
    $.fn.dataTable.moment( 'dd.mm.YYYY' );
    $('#datatable').DataTable({
      "processing": true,
      "serverSide": true,
      <%= @columns.html_safe %>,
      "ajax": $('#datatable').data('source'),
      "pagingType": "full_numbers",
      "bJquerUI": false,
      "iDisplayLength": <%= @rowcount || 25 %>,
      "aLengthMenu": [[10, 25, 100], [10, 25, 100]]
    });
  } );
</script>

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @podcast.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @podcast.category %>
</p>

<p>
  <strong>Itunes url:</strong>
  <%= @podcast.itunes_url %>
</p>

<p>
  <strong>Feed url:</strong>
  <%= @podcast.feed_url %>
</p>

<p>
  <strong>Failed:</strong>
  <%= @podcast.failed %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>